telegram_token: ""
openai_api_key: ""
openai_api_base: null

# Разрешённые пользователи (username или user_id)
allowed_telegram_usernames: []

# Настройки чата
new_dialog_timeout: 600
return_n_generated_images: 1
n_chat_modes_per_page: 5
image_size: "512x512"  # размер для DALL·E
enable_message_streaming: true

# Цены (необязательно менять, но можно для отображения пользователю)
chatgpt_price_per_1000_tokens: 0.0006
gpt_price_per_1000_tokens: 0.0006
whisper_price_per_1_min: 0.006
