telegram_token: "7630787531:AAGjwIi6GGewenb5RT3NpgnArbm3JjMPrxM"
openai_api_key: "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"
openai_api_base: null

# Разрешённые пользователи (username или user_id)
allowed_telegram_usernames: []

# Настройки чата
new_dialog_timeout: 600
return_n_generated_images: 1
n_chat_modes_per_page: 5
image_size: "512x512"  # размер для DALL·E
enable_message_streaming: true

# Цены (необязательно менять, но можно для отображения пользователю)
chatgpt_price_per_1000_tokens: 0.0006
gpt_price_per_1000_tokens: 0.0006
whisper_price_per_1_min: 0.006
