available_text_models: ["gpt-4o-mini"]

info:
  gpt-4o-mini:
    type: chat_completion
    name: GPT-4o Mini
    description: Fast, cost-effective model with multimodal capabilities (text + images). Great for everyday tasks and supports image analysis.

    price_per_1000_input_tokens: 0.00015
    price_per_1000_output_tokens: 0.0006

    scores:
      smart: 4
      fast: 5
      cheap: 5

  dalle-2:
    type: image
    price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006
